/*
 * SPDX-FileCopyrightText: (C) Copyright 2024 Regione Piemonte
 * 
 * SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.vifo.vifobo.util;

public enum ParamsActaEnum {
	OGGETTO_COSMO,
	CODICEIPAENTE_COSMO,
	CODICETIPOLOGIA_COSMO,
	CODICEFISCALE,
	IDAOO,
	REPOSITORYNAME,
	APPKEY,
	CODICE_FRUITORE,
	IDSTRUTTURA,
	IDNODORESP,
	VITALRECORDCODE,
	ORARIO_INIZIO_BOPROC,
	ORARIO_FINE_BOPROC,
	URL_PRATICA,
	URL_UPLOAD,
	URL_DOCUMENTI,
	URL_PROCESSO,
	URL_TOKEN,
	CONSUMER_KEY,
	CONSUMER_SECRET,
	USER_CALLBACK,
	PWD_CALLBACK;
}
