#
#  SPDX-FileCopyrightText: (C) Copyright 2024 Regione Piemonte
#  
#  SPDX-License-Identifier: EUPL-1.2
#
# Il file config.yml definisce i comportamenti che la pipeline deve adottare sul codice sorgente
# e sulle unità di installazione per tutte le fasi del rilascio, dalla build al deployment.
# L'elenco dei valori ammessi e gli esempi di compilazione sono disponibili al link: 

# [OBBLIGATORIO]
# indica in minuscolo il nome del prodotto
productName: vifo

# [OBBLIGATORIO]
# indica in minuscolo il nome della componente
componentName: vifowcl

# [OBBLIGATORIO]
# indica il comportamento da adottare relativamente ai diversi stage della pipeline.
# Alcuni di questi comportamenti possono essere sovrascritti dalla chiamata di una
# pipeline di rilascio dell'intero prodotto
stages:
  build: yes  
  postbuild_test: no
  provision: no
  deploy: no
  postdeploy_test: no
  postdeploy: no

# [OBBLIGATORIO]
build:

  # [OBBLIGATORIO]
  # Se la componente genera più unità di installazione indica se i processi di build di più unità
  # di installazione, possono essere parallelizzati o eseguiti in sequenza
  buildFlow: parallel

  # [OBBLIGATORIO]
  # indica il tipo di tool da utilizzare per la build della componente
  buildTool: npm_node

  # [OBBLIGATORIO]
  # indica la versione del tool di build da utilizzare
  buildToolVersion: node_10_23_2

  # [OBBLIGATORIO]
  # indica l'environment di compilazione da utilizzare
  buildEnvironment: generic

  # [OPZIONALE]
  # mappa che definisce le opzioni di build da apporre al comando, es: -D[property]=[value]
  buildOptionString:

  # [OPZIONALE]
  # mappa che definisce le opzioni di build da apporre al comando es: RepartMaven2GlobalSettings
  mavenSettings: 

# [OPZIONALE]
# Se si desidera copiare uno o più artefatti archiviati in Jenkins da altri progetti,
# indica la lista dei path relativi di diversi workspace dove recuperarli
jobsToCopyFromList:

# [OPZIONALE]
# Se si desidera archiviare a propria volta in Jenkins i propri artefatti
# così da renderli disponibili ad altri progetti Jenkins,
# indica il lor path relativo nel proprio workspace 
targetDir:

# [OPZIONALE]
# indica la lista degli artefatti da archiviare, anche con regexp.
artifactsToArchive: "dist_arch/dist_vifowcl.zip"

# [OBBLIGATORIO]
# indica lo strumento di code review che si vuole adottare.
codeReviewer: 
  sonar:
    node_executable_version: node_14_21_1


# [OBBLIGATORIO]
# indica il comportamento da adottare relativamente alle diverse fasi di test.
# Per ciascuna è possibile indicare se eseguirla e quale strumento utilizzare
test:
  postBuild:
    unitTest:
      active: yes
      tech: junit
  postDeploy:
    apiTest:
      active: yes
      tech: soapui
    uiTest:
      active: yes
      tech: selenium


# [OBBLIGATORIO]
# indica la lista delle unità di installazione derivate dalla build della componente
builds_to_execute:

  # [OBBLIGATORIO]
  # indica il nome dell'unità di installazione, priva di versione ed estensione
  vifowcl:

# [OPZIONALE]
# i seguenti valori di ciascun artefatto, non obbligatori, possono sovrascrivere in tutto
# o in parte quanto definito per l'intera componente relativamente alla build della
# specifica unità di installazione
    customBuildTool: 
    customBuildToolVersion: 
    customBuildEnvironment: 
    customBuildOptionString:
    customProjectToCopyFrom: 
    customArtifactsToCopy: 
    customTargetDir:
    customArtifactsToArchive:
    customMavenSettings:
# [OBBLIGATORIO]
# indica il path relativo nel workspace dove sono creati i pacchetti da caricare su Artifactory
    artifactsToPublish:



