/*
 * SPDX-FileCopyrightText: (C) Copyright 2024 Regione Piemonte
 * 
 * SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.vifo.vifoapi.util.mail;

public enum MailEnum {
	INVIO_DOMANDA_GRATUITA_FIRMATA(1),
	INVIO_DOMANDA_GRATUITA_PROT(2),
	INVIO_DOMANDA_ONEROSA_NO_FIRMA(3),
	INVIO_DOMANDA_ONEROSA_FIRMATA(4),
	INVIO_DOMANDA_ONEROSA_PROT(5),
	INVIO_ASSEGNAZIONE_GRATUITA_NO_FIRMA(6),
	INVIO_ASSEGNAZIONE_ONEROSA_NO_FIRMA(7),
	INVIO_ACCETTAZIONE_ONEROSA_FIRMATA(8),
	INVIO_ACCETTAZIONE_ONEROSA_PROT(9),
	INVIO_RICHIESTA_VARIAZIONI(10),
	TRASFERIMENTO_PARTITA_TIPO_R(11),
	TRASFERIMENTO_PARTITA_TIPO_T(12),
	TRASFERIMENTO_PARTITA_TIPO_R_ACCETTAZIONE(13),
	TRASFERIMENTO_PARTITA_TIPO_T_ACCETTAZIONE(14),
	TRASFERIMENTO_PARTITA_TIPO_R_RIFIUTO(15),
	TRASFERIMENTO_PARTITA_TIPO_T_RIFIUTO(16),
	DOMANDA_RIFIUTATA(17),
	DOMANDA_CHIUSA(18);
	
	
	private int value;
	private MailEnum(int value) {
		this.value = value;
	}
	
	public int getValue() {
		return value;
	}
}
