/*
 * SPDX-FileCopyrightText: (C) Copyright 2024 Regione Piemonte
 * 
 * SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.vifo.vifoapi.util;

public enum ExcelSemiEnum {
	ID_PARTITA_SEMI,
	ID_RIFERIMENTO_PARTITA_FRUTTI,
	CERTIFICATO_PROVENIENZA,
	SPECIE,
	DATA_CERTIFICATO,
	PROVENIENZA,
	TIPO_MATERIALE,
	PRODUTTORE,
	QUANTITA_SCARICO_FRUTTI,
	DATA_CARICO,
	QUANTITA_CARICO,
	QUANTITA_SCARICO_IN_PIANTINE,
	QUANTITA_SCARICO_VENDITA,
	DISTRUZIONE_RIMANENZE,
	QUANTITA_RESIDUA;	
}
