/*
 * SPDX-FileCopyrightText: (C) Copyright 2024 Regione Piemonte
 * 
 * SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.vifo.vifoapi.util;

public enum ExcelPiantineEnum {
	ID_PARTITA_PIANTE,
	ID_RIFERIMENTO_PARTITA_SEMI,
	ID_RIFERIMENTO_PARTITA_PIANTE,
	CERTIFICATO_PROVENIENZA,
	SPECIE,
	DATA_CERTIFICATO,
	PROVENIENZA,
	TIPO_MATERIALE,
	PRODUTTORE,
	ALLEVAMENTO,
	ETA,
	ALTEZZA,
	ANNO_RADICAZIONE_SEME,
	PREZZO_UNITARIO,
	RIFERIMENTO_SCARICO_SEMI_KG,
	DATA_CARICO,
	QUANTITA_TOTALE_N,
	QUANTITA_NON_ASSEGNABILE_N,
	QUANTITA_SCARICO_ALTRE_PIANTE_N,
	QUANTITA_ASSEGNABILE_N,
	QUANTITA_ASSEGNATA_N,
	QUANTITA_RITIRATA_N,
	DISTRUZIONE_RIMANENZE_N,
	QUANTITA_RESIDUA_DISPONIBILE_N,
	POSIZIONE;
}
