/*
 * SPDX-FileCopyrightText: (C) Copyright 2024 Regione Piemonte
 * 
 * SPDX-License-Identifier: EUPL-1.2
*/
package it.csi.vifo.vifoapi.util;

public enum TipoParametroApplEnum {
	ALIQUOTA_IVA,
	ENTE_DIREZIONE,
	ENTE_SETTORE,
	ENTE_CATALOGAZIONE,
	ENTE_INDIRIZZO,
	ENTE_CAP,
	ENTE_COMUNE,
	ENTE_TELEFONO,
	ENTE_MAIL_INFO,
	ENTE_MAIL,
	ENTE_PEC,
	ENTE_DIRIGENTE,
	TEMPLATE_DOMANDA_NOTA,
	TEMPLATE_DOMANDA_PRIVACY_PARAGRAFO,
	TEMPLATE_DOMANDA_PRIVACY_TITOLO,
	CODICE_AUTORIZZATIVO_ATTRIBUITO_DA_SETTORE_FITOSANITARIO,
	TEMPLATE_ASSEGNAZIONE_INDICAZIONI,
	TEMPLATE_ASSEGNAZIONE_COND_VENDITA_TITOLO,
	TEMPLATE_ASSEGNAZIONE_COND_VENDITA_PARAGRAFO,
	TEMPLATE_ASSEGNAZIONE_GRATUITA_INDICAZIONI,
	IPS_CALLBACK_RICEVI_RT_ENABLED,
	AGID_VALIDATION_LINK,
	URL_REDIRECT_LOGOUT;
	
	@Override
	public String toString() {
		return super.toString().replaceAll("_", " ");
	}
}
