/*
 * SPDX-FileCopyrightText: (C) Copyright 2024 Regione Piemonte
 * 
 * SPDX-License-Identifier: EUPL-1.2
*/
/*
 * StatoPratica
 * Aggiornamento dello stato pratica per IDF
 *
 * OpenAPI spec version: 1.0
 * Contact: info@cosmo.csi.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.csi.vifo.vifobo.dto.cosmo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import it.csi.vifo.vifobo.dto.Utente;

/**
 * Tutti i contenuti della pratica aggiornati alla data odierna
 */

@JsonIgnoreProperties
public class AggiornaStatoPraticaRequest {
	private String id = null;
	private String codiceIpaEnte = null;
	private TipoPratica tipo = null;
	private String oggetto = null;
	private StatoPratica stato = null;
	private String riassunto = null;
	private Utente utenteCreazione = null;
	private Date dataCreazione = null;
	private Date dataFine = null;
	private Date dataCambioStato = null;
	private Date dataAggiornamento = null;
	private Object metadati = null;
	private List<Attivita> attivita = null;
	private List<Messaggio> commenti = null;
	private List<Documento> documenti = null;
	private String refURL = null;

	public AggiornaStatoPraticaRequest id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Get id
	 * 
	 * @return id
	 **/
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public AggiornaStatoPraticaRequest codiceIpaEnte(String codiceIpaEnte) {
		this.codiceIpaEnte = codiceIpaEnte;
		return this;
	}

	/**
	 * Get codiceIpaEnte
	 * 
	 * @return codiceIpaEnte
	 **/

	public String getCodiceIpaEnte() {
		return codiceIpaEnte;
	}

	public void setCodiceIpaEnte(String codiceIpaEnte) {
		this.codiceIpaEnte = codiceIpaEnte;
	}

	public AggiornaStatoPraticaRequest tipo(TipoPratica tipo) {
		this.tipo = tipo;
		return this;
	}

	/**
	 * Get tipo
	 * 
	 * @return tipo
	 **/

	public TipoPratica getTipo() {
		return tipo;
	}

	public void setTipo(TipoPratica tipo) {
		this.tipo = tipo;
	}

	public AggiornaStatoPraticaRequest oggetto(String oggetto) {
		this.oggetto = oggetto;
		return this;
	}

	/**
	 * Get oggetto
	 * 
	 * @return oggetto
	 **/

	public String getOggetto() {
		return oggetto;
	}

	public void setOggetto(String oggetto) {
		this.oggetto = oggetto;
	}

	public AggiornaStatoPraticaRequest stato(StatoPratica stato) {
		this.stato = stato;
		return this;
	}

	/**
	 * Get stato
	 * 
	 * @return stato
	 **/

	public StatoPratica getStato() {
		return stato;
	}

	public void setStato(StatoPratica stato) {
		this.stato = stato;
	}

	public AggiornaStatoPraticaRequest riassunto(String riassunto) {
		this.riassunto = riassunto;
		return this;
	}

	/**
	 * Get riassunto
	 * 
	 * @return riassunto
	 **/

	public String getRiassunto() {
		return riassunto;
	}

	public void setRiassunto(String riassunto) {
		this.riassunto = riassunto;
	}

	public AggiornaStatoPraticaRequest utenteCreazione(Utente utenteCreazione) {
		this.utenteCreazione = utenteCreazione;
		return this;
	}

	/**
	 * Get utenteCreazione
	 * 
	 * @return utenteCreazione
	 **/

	public Utente getUtenteCreazione() {
		return utenteCreazione;
	}

	public void setUtenteCreazione(Utente utenteCreazione) {
		this.utenteCreazione = utenteCreazione;
	}

	public AggiornaStatoPraticaRequest dataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
		return this;
	}

	/**
	 * Get dataCreazione
	 * 
	 * @return dataCreazione
	 **/

	public Date getDataCreazione() {
		return dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	public AggiornaStatoPraticaRequest dataFine(Date dataFine) {
		this.dataFine = dataFine;
		return this;
	}

	/**
	 * Get dataFine
	 * 
	 * @return dataFine
	 **/

	public Date getDataFine() {
		return dataFine;
	}

	public void setDataFine(Date dataFine) {
		this.dataFine = dataFine;
	}

	public AggiornaStatoPraticaRequest dataCambioStato(Date dataCambioStato) {
		this.dataCambioStato = dataCambioStato;
		return this;
	}

	/**
	 * Get dataCambioStato
	 * 
	 * @return dataCambioStato
	 **/

	public Date getDataCambioStato() {
		return dataCambioStato;
	}

	public void setDataCambioStato(Date dataCambioStato) {
		this.dataCambioStato = dataCambioStato;
	}

	public AggiornaStatoPraticaRequest dataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
		return this;
	}

	/**
	 * Get dataAggiornamento
	 * 
	 * @return dataAggiornamento
	 **/

	public Date getDataAggiornamento() {
		return dataAggiornamento;
	}

	public void setDataAggiornamento(Date dataAggiornamento) {
		this.dataAggiornamento = dataAggiornamento;
	}

	public AggiornaStatoPraticaRequest metadati(Object metadati) {
		this.metadati = metadati;
		return this;
	}

	/**
	 * metadati della pratica in formato libero
	 * 
	 * @return metadati
	 **/
	public Object getMetadati() {
		return metadati;
	}

	public void setMetadati(Object metadati) {
		this.metadati = metadati;
	}

	public AggiornaStatoPraticaRequest attivita(List<Attivita> attivita) {
		this.attivita = attivita;
		return this;
	}

	public AggiornaStatoPraticaRequest addAttivitaItem(Attivita attivitaItem) {
		if (this.attivita == null) {
			this.attivita = new ArrayList<Attivita>();
		}
		this.attivita.add(attivitaItem);
		return this;
	}

	/**
	 * array di tutte le attività della pratica in ordine cronologico, le attività
	 * concluse hanno dataFine not null
	 * 
	 * @return attivita
	 **/
	public List<Attivita> getAttivita() {
		return attivita;
	}

	public void setAttivita(List<Attivita> attivita) {
		this.attivita = attivita;
	}

	public AggiornaStatoPraticaRequest commenti(List<Messaggio> commenti) {
		this.commenti = commenti;
		return this;
	}

	public AggiornaStatoPraticaRequest addCommentiItem(Messaggio commentiItem) {
		if (this.commenti == null) {
			this.commenti = new ArrayList<Messaggio>();
		}
		this.commenti.add(commentiItem);
		return this;
	}

	/**
	 * array in ordine cronologico dei commenti della pratica
	 * 
	 * @return commenti
	 **/
	public List<Messaggio> getCommenti() {
		return commenti;
	}

	public void setCommenti(List<Messaggio> commenti) {
		this.commenti = commenti;
	}

	public AggiornaStatoPraticaRequest documenti(List<Documento> documenti) {
		this.documenti = documenti;
		return this;
	}

	public AggiornaStatoPraticaRequest addDocumentiItem(Documento documentiItem) {
		if (this.documenti == null) {
			this.documenti = new ArrayList<Documento>();
		}
		this.documenti.add(documentiItem);
		return this;
	}

	/**
	 * array dei documenti della pratica
	 * 
	 * @return documenti
	 **/
	public List<Documento> getDocumenti() {
		return documenti;
	}

	public void setDocumenti(List<Documento> documenti) {
		this.documenti = documenti;
	}

	/**
	 * @return the refURL
	 */
	public String getRefURL() {
		return refURL;
	}

	/**
	 * @param refURL the refURL to set
	 */
	public void setRefURL(String refURL) {
		this.refURL = refURL;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		AggiornaStatoPraticaRequest aggiornaStatoPraticaRequest = (AggiornaStatoPraticaRequest) o;
		return Objects.equals(this.id, aggiornaStatoPraticaRequest.id)
				&& Objects.equals(this.codiceIpaEnte, aggiornaStatoPraticaRequest.codiceIpaEnte)
				&& Objects.equals(this.tipo, aggiornaStatoPraticaRequest.tipo)
				&& Objects.equals(this.oggetto, aggiornaStatoPraticaRequest.oggetto)
				&& Objects.equals(this.stato, aggiornaStatoPraticaRequest.stato)
				&& Objects.equals(this.riassunto, aggiornaStatoPraticaRequest.riassunto)
				&& Objects.equals(this.utenteCreazione, aggiornaStatoPraticaRequest.utenteCreazione)
				&& Objects.equals(this.dataCreazione, aggiornaStatoPraticaRequest.dataCreazione)
				&& Objects.equals(this.dataFine, aggiornaStatoPraticaRequest.dataFine)
				&& Objects.equals(this.dataCambioStato, aggiornaStatoPraticaRequest.dataCambioStato)
				&& Objects.equals(this.dataAggiornamento, aggiornaStatoPraticaRequest.dataAggiornamento)
				&& Objects.equals(this.metadati, aggiornaStatoPraticaRequest.metadati)
				&& Objects.equals(this.attivita, aggiornaStatoPraticaRequest.attivita)
				&& Objects.equals(this.commenti, aggiornaStatoPraticaRequest.commenti)
				&& Objects.equals(this.documenti, aggiornaStatoPraticaRequest.documenti)
				&& Objects.equals(this.refURL, aggiornaStatoPraticaRequest.refURL)
				;
	}

	@Override
	public int hashCode() {
		return Objects.hash(id, codiceIpaEnte, tipo, oggetto, stato, riassunto, utenteCreazione, dataCreazione,
				dataFine, dataCambioStato, dataAggiornamento, metadati, attivita, commenti, documenti, refURL);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class AggiornaStatoPraticaRequest {\n");

		sb.append("    id: ").append(toIndentedString(id)).append("\n");
		sb.append("    codiceIpaEnte: ").append(toIndentedString(codiceIpaEnte)).append("\n");
		sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
		sb.append("    oggetto: ").append(toIndentedString(oggetto)).append("\n");
		sb.append("    stato: ").append(toIndentedString(stato)).append("\n");
		sb.append("    riassunto: ").append(toIndentedString(riassunto)).append("\n");
		sb.append("    utenteCreazione: ").append(toIndentedString(utenteCreazione)).append("\n");
		sb.append("    dataCreazione: ").append(toIndentedString(dataCreazione)).append("\n");
		sb.append("    dataFine: ").append(toIndentedString(dataFine)).append("\n");
		sb.append("    dataCambioStato: ").append(toIndentedString(dataCambioStato)).append("\n");
		sb.append("    dataAggiornamento: ").append(toIndentedString(dataAggiornamento)).append("\n");
		sb.append("    metadati: ").append(toIndentedString(metadati)).append("\n");
		sb.append("    attivita: ").append(toIndentedString(attivita)).append("\n");
		sb.append("    commenti: ").append(toIndentedString(commenti)).append("\n");
		sb.append("    documenti: ").append(toIndentedString(documenti)).append("\n");
		sb.append("    refURL: ").append(toIndentedString(refURL)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
